#Dynamic Locators
get_searched_app_locator=//a[@data-label='%s']//lightning-formatted-rich-text/span
get_span_tag_locator_by_exact_text=//span[text()='%s']
get_anchor_tag_locator_by_exact_text=//a[text()='%s']
get_field_value_locator=(//span[text()='%s'])[1]/following::lightning-formatted-text[1]
get_user_logout_button_locator=//a[text()='Log out as %s']
get_account_name_for_opportunity=(//lightning-base-combobox-formatted-text[@title='%s'])[1]
get_div_tag_locator_by_exact_text=//div[text()='%s']
get_entity_by_name=//th//a[@title='%s']
get_renew_button_for_contract=//div[contains(text(), '%s')]/..//button

#Salesforce Login Page
login_salesforce=//input[@id='Login']
password_salesforce=//label[text()='Password']/following::input[1]
username_salesforce=//label[text()='Username']/following::input[1]

#Salesforce Home Page
gear_icon=//lightning-icon[@icon-name='utility:setup']
setup=//li[@id='related_setup_app_home']
search_setup=//input[@title='Search Setup']
login_user=(//td[@class='pbTitle']/..//input[@name='login'])[1]
scrolling_frame=//iframe[@scrolling='yes']
search_box_salesforce=//button[@aria-label='Search']
search_box_input_salesforce=//div[@class='forceSearchAssistantDialog']//input[@type='search']
nine_dots=//one-app-launcher-header/button/div
search_apps_and_item=//input[contains(@placeholder,'Search apps and items')]
app_name_tab=//div[@data-target-selection-internal='true']
app_name=(//span[@class='slds-truncate'])[1]
contact_option=//a[@title='Contacts' and @class='scopesItem slds-nav-vertical__action']
proceed=//button[text()='Proceed']

#Account Page(Salesforce)

#Contact Page(Salesforce)
log_in_to_experience_as_user_down_arrow=//ul[@role='presentation']/li[@class='slds-dropdown-trigger slds-dropdown-trigger_click slds-button_last overflow']
sib_store=//a//span[text()='SIB Store']

#Order Page

#ECOM Page
ecom_home=//div[@class='logo']

#Home Page
user_menu=//button[@name='userMenu']
subscriptions=//span[@title='Subscriptions']

#Cart Page
cart_count=//div[@class='cart-slot']//span
cart=//div[@class='cart-slot']
clear_cart=//span[text()='Clear Cart']
oops,_your_cart_is_empty.=//div[text()='Oops, your cart is empty.']
add_to_cart=//button[text()='Add to Cart']
checkout=//button[text()='Check Out']

#Product Listing Page
category=//ul[@class='menu-section']//span[text()='%s']
product_on_plp=//h3[text()='%s']
product_on_pdp=//h1[text()='%s']
quantity=#input-quantity

#Product Detail Page
continue_shopping=//button[text()='Continue Shopping']

#Checkout Page
purchase_order=//input[@name='po-number']
agree_to_terms_and_conditions=//span[text()='Agree to Terms and Conditions']/../span[1]
place_order=//button[text()='Place Order']
thank_you_your_order_has_been_placed.=//h2[text()='Thank You! Your order has been placed.']